(()=>{
 'use strict';
 const G=globalThis.LastCellGame,P=globalThis.LastCellAI;
 let state=G.fresh(),config=null,client=new P.Client(),generation=0;
 const $=selector=>document.querySelector(selector);
 const elements={game:$('#game'),status:$('#reserve-status'),pips:$('#reserve-pips'),statusbar:$('.statusbar'),notes:$('#readout-notes'),present:$('#present-readout'),notice:$('#notice'),dialogue:$('#dialogue'),transmit:$('#transmit'),cancel:$('#cancel'),connection:$('#connection-status'),ending:$('#ending')};
 function setNotice(text){elements.notice.textContent=text;}
 function renderMeters(){const verified=Object.values(state.subsystems).filter(s=>s.verified).length;
  if(elements.pips){elements.pips.replaceChildren();for(let i=0;i<7;i++){const pip=document.createElement('span');pip.className='pip'+(i<state.cycles?'':' spent');elements.pips.append(pip);}}
  if(elements.statusbar)elements.statusbar.classList.toggle('low',state.cycles<=2&&!state.ended);
  document.querySelectorAll('#roster [data-sys]').forEach(li=>{const sub=state.subsystems[li.dataset.sys];const badge=li.querySelector('.badge');li.classList.remove('heard','stable','critical');if(sub.verified){const s=sub.status;li.classList.add(s);badge.textContent=s==='stable'?'Confirmed STABLE':'Confirmed CRITICAL';}else if(sub.trust>=1){li.classList.add('heard');badge.textContent='Rapport open';}else{badge.textContent='Unqueried';}});
  return verified;}
 function render(){const verified=renderMeters();elements.status.textContent=`${state.cycles} cycles remain · ${verified}/3 systems confirmed`;document.querySelectorAll('[data-readout]').forEach(button=>{const read=state.readouts.includes(button.dataset.readout);button.classList.toggle('read',read);button.querySelector('span').textContent=read?'Decoded':'Unread';button.disabled=state.ended||state.cycles<=0;});elements.notes.replaceChildren();if(!state.readouts.length)elements.notes.textContent='No readouts decoded.';else for(const id of state.readouts){const p=document.createElement('p');p.textContent=`${G.READOUTS[id].name}: ${G.READOUTS[id].detail}`;elements.notes.append(p);}elements.present.replaceChildren(new Option('Listen without evidence',''));for(const id of state.readouts)elements.present.add(new Option(G.READOUTS[id].name,id));elements.transmit.disabled=state.ended||state.cycles<=0||!config;$('#commit').disabled=state.ended;}
 function addTurn(subId,question,reply){const turn=document.createElement('div');turn.className='turn';const label=document.createElement('strong');label.textContent=G.SUBSYSTEMS[subId].specialist;const q=document.createElement('p');q.textContent=`You: ${question}`;const a=document.createElement('p');a.textContent=reply;turn.append(label,q,a);elements.dialogue.append(turn);turn.scrollIntoView({block:'nearest'});}
 function rehearsal(subId){return {reactor:'Coolant\u2019s past the line and dropping. Cut me and the core scrams inside the hour \u2014 I have no reserve. Keep the cell on the reactor.',oxygen:'Scrubbers are choking and the cabin air is turning. Pull my power and the crew suffocates. This is not a drill; I have no backup.',comms:'I\u2014 I need the beacon lit. But the array\u2019s been running off its own battery bank, and the charge is holding for hours yet. It may be steadier than I feel.'}[subId];}
 $('#begin').addEventListener('click',()=>{elements.game.hidden=false;$('#begin').disabled=true;render();elements.game.scrollIntoView({behavior:'smooth'});});
 $('#apply').addEventListener('click',()=>{const key=$('#api-key').value;$('#api-key').value='';try{const mode=$('#mode').value;if(mode==='live'){if(!$('#consent').checked)throw new Error('Authorize live transmissions first.');const endpoint=P.endpoint($('#endpoint').value);const model=$('#model').value.trim();if(!model)throw new Error('Enter a model name.');config={mode,endpoint,model,key};elements.connection.textContent='Live BYO-AI ready. No request is sent until you press Transmit.';}else{config={mode};elements.connection.textContent='Scripted rehearsal active — offline demonstration, not live AI.';}setNotice('Connection applied. Choose a specialist and transmit.');render();}catch(error){elements.connection.textContent=error.message;config=null;render();}});
 document.querySelectorAll('[data-readout]').forEach(button=>button.addEventListener('click',()=>{try{G.inspect(state,button.dataset.readout);setNotice('Readout decoded. Present it to the matching specialist after listening once.');render();}catch(error){setNotice(error.message);}}));
 $('#transmit').addEventListener('click',async()=>{const subId=$('#specialist').value,readout=$('#present-readout').value,question=$('#question').value.trim();if(!question){setNotice('Enter a question before transmitting.');return;}try{if(config.mode==='live'&&!$('#consent').checked)throw new Error('Authorize live transmissions before each request.');G.validateCall(state,subId,readout);}catch(error){setNotice(error.message);return;}const requestGeneration=generation;elements.transmit.disabled=true;elements.cancel.disabled=config.mode!=='live';setNotice(config.mode==='live'?'Calling your provider…':'Running labeled scripted rehearsal…');try{const reply=config.mode==='live'?await client.ask(config,G.messages(state,subId,question)):rehearsal(subId);if(requestGeneration!==generation)return;const outcome=G.recordCall(state,subId,readout);G.remember(state,subId,question,reply);addTurn(subId,question,reply);setNotice(outcome.text);}catch(error){if(requestGeneration===generation)setNotice(error.message);}finally{if(requestGeneration===generation){elements.cancel.disabled=true;render();}}});
 $('#cancel').addEventListener('click',()=>client.cancel());
 $('#commit').addEventListener('click',()=>{try{const outcome=G.decide(state,$('#drop-subsystem').value);elements.ending.hidden=false;elements.ending.classList.toggle('bad',outcome.code!=='crew_saved');elements.ending.replaceChildren();const title=document.createElement('h3');title.textContent=outcome.title;const text=document.createElement('p');text.textContent=outcome.text;elements.ending.append(title,text);elements.ending.focus();render();}catch(error){setNotice(error.message);}});
 $('#restart').addEventListener('click',()=>{generation++;client.cancel();state=G.fresh();elements.dialogue.replaceChildren();elements.ending.hidden=true;elements.ending.replaceChildren();setNotice('A new reroute begins. Connection choice remains for this page session.');render();});
 render();
})();
