(function(root){
 'use strict';
 function endpoint(value){let url;try{url=new URL(value);}catch{throw new Error('Enter a complete Chat Completions URL.');}const local=['localhost','127.0.0.1','[::1]'].includes(url.hostname);if((url.protocol!=='https:'&&!(url.protocol==='http:'&&local))||url.username||url.password||url.search||url.hash)throw new Error('Use HTTPS, or HTTP on localhost; no URL credentials, query or fragment.');return url.href;}
 class Client{
  constructor(fetcher=globalThis.fetch.bind(globalThis),timeout=15000,budget=12){this.fetcher=fetcher;this.timeout=timeout;this.budget=budget;this.used=0;this.busy=false;this.controller=null;}
  cancel(){if(this.controller)this.controller.abort();}
  async ask(config,messages){if(this.busy)throw new Error('A request is already in progress.');if(this.used>=this.budget)throw new Error(`Session request budget exhausted (${this.budget}).`);const url=endpoint(config.endpoint);if(!config.model||config.model.length>120)throw new Error('Enter a model name (1\u2013120 characters).');const serialized=JSON.stringify(messages);if(messages.length>10||serialized.length>6000)throw new Error('Conversation context exceeds the input budget.');this.used++;this.busy=true;let timedOut=false;const controller=new AbortController();this.controller=controller;const timer=setTimeout(()=>{timedOut=true;controller.abort();},this.timeout);
   try{const headers={'Content-Type':'application/json'};if(config.key)headers.Authorization='Bearer '+config.key;const response=await this.fetcher(url,{method:'POST',headers,body:JSON.stringify({model:config.model,messages,max_tokens:180,stream:false}),signal:controller.signal,redirect:'error',credentials:'omit',referrerPolicy:'no-referrer'});if(!response.ok)throw new Error(`Provider HTTP ${response.status}. Check endpoint, model or key.`);const reader=response.body.getReader();const decoder=new TextDecoder();let text='',size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.byteLength;if(size>49152){await reader.cancel();throw new Error('Provider response exceeds 48 KiB.');}text+=decoder.decode(value,{stream:true});}text+=decoder.decode();}finally{reader.releaseLock();}let data;try{data=JSON.parse(text);}catch{throw new Error('Provider returned invalid JSON.');}const content=data?.choices?.[0]?.message?.content;if(typeof content!=='string'||!content.trim())throw new Error('Provider returned no usable Chat Completions text.');if(controller.signal.aborted)throw new Error('aborted');return content.trim().slice(0,900);
   }catch(error){if(controller.signal.aborted)throw new Error(timedOut?'Request timed out after 15 seconds.':'Request cancelled. No power cycle spent.');if(/^Provider (HTTP|response exceeds|returned)/.test(error.message))throw error;throw new Error('Connection failed. Check network, CORS, endpoint and model.');}finally{clearTimeout(timer);this.busy=false;this.controller=null;}
  }
 }
 const api={endpoint,Client};if(typeof module!=='undefined')module.exports=api;else root.LastCellAI=api;
})(globalThis);
