(()=>{
 'use strict';
 const G=globalThis.LanternGame,P=globalThis.LanternAI;
 let state=G.fresh(),config=null,client=new P.Client(),generation=0;
 const $=selector=>document.querySelector(selector);
 const elements={game:$('#game'),status:$('#watch-status'),notes:$('#signal-notes'),present:$('#present-signal'),notice:$('#notice'),dialogue:$('#dialogue'),transmit:$('#transmit'),cancel:$('#cancel'),connection:$('#connection-status'),ending:$('#ending')};
 function setNotice(text){elements.notice.textContent=text;}
 function render(){elements.status.textContent=`${state.beats} watches remain · ${Object.values(state.vessels).filter(v=>v.confirmed).length}/2 routes confirmed`;document.querySelectorAll('[data-signal]').forEach(button=>{const read=state.signals.includes(button.dataset.signal);button.classList.toggle('read',read);button.querySelector('span').textContent=read?'Decoded':'Unread';button.disabled=state.ended||state.beats<=0;});elements.notes.replaceChildren();if(!state.signals.length)elements.notes.textContent='No signals decoded.';else for(const id of state.signals){const p=document.createElement('p');p.textContent=`${G.SIGNALS[id].name}: ${G.SIGNALS[id].detail}`;elements.notes.append(p);}elements.present.replaceChildren(new Option('Listen without evidence',''));for(const id of state.signals)elements.present.add(new Option(G.SIGNALS[id].name,id));elements.transmit.disabled=state.ended||state.beats<=0||!config;$('#commit').disabled=state.ended;}
 function addTurn(captain,question,reply){const turn=document.createElement('div');turn.className='turn';const label=document.createElement('strong');label.textContent=G.VESSELS[captain].captain;const q=document.createElement('p');q.textContent=`You: ${question}`;const a=document.createElement('p');a.textContent=reply;turn.append(label,q,a);elements.dialogue.append(turn);turn.scrollIntoView({block:'nearest'});}
 function rehearsal(captain){return captain==='ferry'?'The Morrow Bell draws little water. Keep the north lamp steady and I can carry the passengers across the shoal before the heavier ship.':'Ashwing will not answer her helm. Let the ferry clear first, then send the harbor tug to my lee side.';}
 $('#begin').addEventListener('click',()=>{elements.game.hidden=false;$('#begin').disabled=true;render();elements.game.scrollIntoView({behavior:'smooth'});});
 $('#apply').addEventListener('click',()=>{const key=$('#api-key').value;$('#api-key').value='';try{const mode=$('#mode').value;if(mode==='live'){if(!$('#consent').checked)throw new Error('Authorize live transmissions first.');const endpoint=P.endpoint($('#endpoint').value);const model=$('#model').value.trim();if(!model)throw new Error('Enter a model name.');config={mode,endpoint,model,key};elements.connection.textContent='Live BYO-AI ready. No request is sent until you press Transmit.';}else{config={mode};elements.connection.textContent='Scripted rehearsal active — offline demonstration, not live AI.';}setNotice('Connection applied. Choose a captain and transmit.');render();}catch(error){elements.connection.textContent=error.message;config=null;render();}});
 document.querySelectorAll('[data-signal]').forEach(button=>button.addEventListener('click',()=>{try{G.inspect(state,button.dataset.signal);setNotice('Signal decoded. Present it to the matching captain after listening once.');render();}catch(error){setNotice(error.message);}}));
 $('#transmit').addEventListener('click',async()=>{const captain=$('#captain').value,signal=$('#present-signal').value,question=$('#question').value.trim();if(!question){setNotice('Enter a question before transmitting.');return;}try{if(config.mode==='live'&&!$('#consent').checked)throw new Error('Authorize live transmissions before each request.');G.validateCall(state,captain,signal);}catch(error){setNotice(error.message);return;}const requestGeneration=generation;elements.transmit.disabled=true;elements.cancel.disabled=config.mode!=='live';setNotice(config.mode==='live'?'Calling your provider…':'Running labeled scripted rehearsal…');try{const reply=config.mode==='live'?await client.ask(config,G.messages(state,captain,question)):rehearsal(captain);if(requestGeneration!==generation)return;const outcome=G.recordCall(state,captain,signal);G.remember(state,captain,question,reply);addTurn(captain,question,reply);setNotice(outcome.text);}catch(error){if(requestGeneration===generation)setNotice(error.message);}finally{if(requestGeneration===generation){elements.cancel.disabled=true;render();}}});
 $('#cancel').addEventListener('click',()=>client.cancel());
 $('#commit').addEventListener('click',()=>{try{const outcome=G.decide(state,$('#first-vessel').value,$('#tug-order').value);elements.ending.hidden=false;elements.ending.classList.toggle('bad',outcome.code!=='safe_harbor');elements.ending.replaceChildren();const title=document.createElement('h3');title.textContent=outcome.title;const text=document.createElement('p');text.textContent=outcome.text;elements.ending.append(title,text);elements.ending.focus();render();}catch(error){setNotice(error.message);}});
 $('#restart').addEventListener('click',()=>{generation++;client.cancel();state=G.fresh();elements.dialogue.replaceChildren();elements.ending.hidden=true;elements.ending.replaceChildren();setNotice('A new watch begins. Connection choice remains for this page session.');render();});
 render();
})();
